from bs4 import BeautifulSoup
from bs4.element import Comment
import urllib.request
import time
import pickle
from docx import Document
from docx.enum.text import WD_LINE_SPACING
from docx.enum.style import WD_STYLE_TYPE
from docx.shared import Pt
from docx.shared import Inches
from docx.enum.text import WD_PARAGRAPH_ALIGNMENT
from docx.enum.section import WD_ORIENTATION
#from content import report_content, provinces, report_date, introduction, intro_content
alignment_dict = {'justify': WD_PARAGRAPH_ALIGNMENT.JUSTIFY,
                  'center': WD_PARAGRAPH_ALIGNMENT.CENTER,
                  'centre': WD_PARAGRAPH_ALIGNMENT.CENTER,
                  'right': WD_PARAGRAPH_ALIGNMENT.RIGHT,
                  'left': WD_PARAGRAPH_ALIGNMENT.LEFT}

orientation_dict = {'portrait': WD_ORIENTATION.PORTRAIT,
                    'landscape': WD_ORIENTATION.LANDSCAPE}
                    
def add_content(content, space_after, font_name=None, font_size=16, line_spacing=0, space_before=0,
                align='justify', keep_together=True, keep_with_next=False, page_break_before=False,
                widow_control=False, set_bold=False, set_italic=False, set_underline=False, set_all_caps=False,style_name=""):
    paragraph = document.add_paragraph(content)
    if style_name!="":
        paragraph.style = document.styles.add_style(style_name, WD_STYLE_TYPE.PARAGRAPH)
    font = paragraph.style.font
    font.name = font_name
    font.size = Pt(font_size)
    font.bold = set_bold
    font.italic = set_italic
    font.all_caps = set_all_caps
    font.underline = set_underline
    paragraph_format = paragraph.paragraph_format
    paragraph_format.alignment = alignment_dict.get(align.lower())
    paragraph_format.space_before = Pt(space_before)
    paragraph_format.space_after = Pt(space_after)
    paragraph_format.line_spacing = line_spacing
    paragraph_format.keep_together = keep_together
    paragraph_format.keep_with_next = keep_with_next
    paragraph_format.page_break_before = page_break_before
    paragraph_format.widow_control = widow_control




#add_content(t3[1].strip(), align='Left', space_before=0, space_after=0, line_spacing=1,font_size=12,
#            set_bold=False, set_all_caps=False, set_underline=True, style_name ="Normal2")


#word_list = ["fin","reconcile","throttle","spectator","jihad","umpire","uprising","steroid",
#             "crumb","edible","provincial","puddle","gravel","vengeance","martyr","tug","disciple",
#             "integral","sneaky","drape","imaging","sergeant","cram","erode","jab","buff","catalyst",
#             "oppression","turbine","artillery","bilateral","gruesome","prospective","ripple","rout","eject",
#             "propietary","sage","topple","tribunal","populist","flex","dangle","arsenal","exploitation","conjure","mould"]

#word_list = ["spiral","inflict","scrutiny","smuggle","rug","loot","cement","reel","dissolve","rhetoric","bash","feat","sniff","constitution","tumble","prototype","champ","restrain","elf","pupil","heroic","parliamentary","hustle","artefact","exotic","gag","smack","militia","wicket","bout","petrol","woo","accountable","boogie","swipe","terrain","groove","hose","fuse","thug","moron","banner","parole","contemplate","skeleton","cemetery","suppress"]
#word_list = ["assert","canal","embed","intact","confine","calf","roam","wit","prank","ideology","inherent","disgrace","spine","martial","animation","tactical","infamous","interrogate","innit","pistol","relentless","embark","midst","autopsy","harness","stroll","rotten","tourism","aye","ensemble","youngster","crocodile","ward","erupt","manifest","lump","ruthless","abide","oblige","weep","flock","alibi","lethal","despair","scrape","flare","cone"]
#word_list = ["feud","notch","compatible","glamour","divert","heap","dread","backlash","fuss","sorrow","tickle","torch","dwell","retaliate","rattle","dart","stagger","interim","warfare","endeavour","indigenous","aspire","carriage","persistent","perimeter","thrust","autograph","ambush","blossom","sanctuary","indulge","node","poop","nolecule","charter","commissioner","petty","cub","spec","renown","scroll","nun","flap","flick","trench","ammunition","hype"]
#word_list = ["strive","bunker","consensus","homicide","savage","filthy","unto","shelve","mourn","quantum","plasma","corridor","limb","arse","bloke","aesthetic","crave","coup","scout","sequel","booze","caption","weave","brace","propaganda","provoke","dense","sub","alley","disclosure","traitor","asteroid","yacht","manoeuvre","stalk","ballot","cling","lash","snatch","hedge","heroin","habitat","syndrome","vault","drip","loom","pinch"]
#word_list = ["section1","nefarious","parsley","stoop","unequivocal","foliage","ldyllic","puberty","resuscitate","sulphur","volt","admittedly","clergy","deranged","dusk","exude","interstate","lug","solemn","anaesthesia","backfire","pharmacist","pinnacle","strife","brotherhood","colonize","detrimental","duouche","expanse","flamboyant","intolerance","ministerial","noose","penchant","sham","affluent","complicit","ethanol","phial","plume","twilight","fest","pervasive","regent","subside","voodoo","taxation","section2","apertheid","equilibrium","porridge","reprimand","swerve","acrylic","affirmative","debilitate","eletrician","hysteria","persuasion","tiara","cheerleading","disengage","hyena","accrue","devoid","null","procedural","reluctance","tolerant","converse","countryman","freshwater","guise","lynch","peddle","precursor","ruse","slag","actionable","bask","hammock","inundate","lefty","repression","speck","bloodline","bonkers","clueless","relinquish","sentient","shabby","stutter","volley","yawn","section3","bonnet","cornerstone","everlasting","inaugurate","paramilitary","carer","deflate","herein","quantitative","redirect","refrigerate","sloth","squeal","sterilize","heterosexual","raffle","wilt","bipolar","cardio","cocoon","corset","feral","foray","indestructible","simulator","botch","caricature","compliant","coop","dung","familiarity","impasse","incense","mockery","munch","pulmonary","repetoirie","wildcat","buttock","dandy","dismal","redhead","trough","upstate","egregious","implore","section4","mumble","pedestal","ply","ratify","tavern","coerce","consummate","converter","impart","ruff","unheaval","ceasefire","contradictory","dehydrated","nightfall","petrify","shoreline","attest","barrister","dialysis","sequential","ahem","halo","procrastinate","provocatiion","shriek","attentive","casserole","delicatessen","irreversible","marquee","palpable","physiological","weasel","gloat","pant","pelvis","playback","scathing","uproar","acronym","astronomy","circumstantial","floppy","fluke","dolly","section5","grotesque","slimy","snot","swag","transitional","archetype","frateful","fluff","illegitimate","clientele","freeder","painstaking","professionalism","rediscover","strew","cornerback","reliever","rink","apprehension","decode","overlay","perseverance","stringent","fennel","gymnast","reprint","telegraph","vend","counteract","pallet","accessibility","adultery","demote","incessant","individuality","resolute","rye","tarnish","variance","abate","margarita","shoo","fishery","navigational","perennial","comprehension"]
#word_list = ["section6","rife","taper","thermometer","eloquent","heyday","obituary","gnome","hasty","rebate","refurbish","snappy","unnerve","vandalism","befall","conundrum","devotee","eruption","exaggeration","indiscriminate","novice","preposterous","shipwreck","tastefuly","willy","coax","embezzle","frontal","mast","persevere","snob","trampoline","underpin","underrate","cobble","deodorant","resurgence","shaker","calamity","citation","domesticate","extraterrestrial","finesse","guild","intolerant","lawless","modular","section7","folklore","prairie","serene","trusty","airbrush","braid","culmination","fruition","officiate","owag","brittle","emblem","gratification","insomnia","insurgency","pelvic","scribble","skunk","squander","acidity","caveat","creed","devout","grove","humid","kosher","mulnutrition","neutrality","nought","chirp","manpower","ovary","polyester","prevalence","sect","synthesize","bloodstream","embodiment","inflame","mosaic","skeptic","bale","crackle","mastery","rewid","snooze","section8","gaunlet","remand","wart","wont","impartial","lunge","nautical","pitiful","commercialization","embolden","feisty","porcelain","untold ","uwinnings","choreograph","cordon","pastel","preset","shenanigans","bewilder","suction","thermostat","alight","chameleon","crossbow","exorcism","mime","momentous","reggae","sculptor","sdeiment","stroller","temperament","adolescence","composure","consortium","fielder","nestle","proton","sissy","apologetic","disgruntled","fad","garrison","snub","section9","cusp","indecent","llama","nitrate","picket","prodigy","carousel","clout","mac","magnesium","mediate","melancholy","noteworthy","profiling","quadruple","aerospace","collate","decadent","morbid","punitive","sugary","tat","generational","impunity","mouthful","troublesome","undercut","cleric","implicit","lineman","perverse","potty","dilate","groovy","labyrinth","parchment","phobia","scandalous","spasm","tailgate","amber","augmentation","condescend","occupancy","watery","section10","evasive","flinch","syntax","tram","urn","enrichment","manor","mutter","percussion","profess","stretcher","untreated","washer","decry","moat","populism","reactive","stagnant","wannabe","airlock","contraception","ebb","expressive","instigate","notwithstanding","telecommunications","untouchable","abnomality","debacle","falsehood","manure","outgrow","plentiful","smirk","wiolet","agility","allot","craftsmanship","disllusioned","ejaculate","evasion","gild","infer","languish","logistically"]
#word_list = ["section11","dealership","exemplary","expulsion","forgery","freckle","grader","hiss","indentifiable","plait","trivia","unintended","bearish","blemish","brunt","coriander","dab","desecrate","feline","legalization","rarity","replenish","spectral","abstain","clasp","cologne","din","dole","haste","adaptive","brig","bureaucratic","cot","perplex","solace","avant","compilation","evious","knickers","lifepan","skimpy","unspeakable","crafty","cyst","eminent","inhibition","section12","lymphoma","symopathize","tumultuous","embroidery","gape","grumble","scapegoat","standstill","toxicity","dogged","huff","refute","storied","testimonial","consulate","fern","leaflet","otter","unorthodox","extravaganza","modest","quell","sensual","wring","contraption","detachment","liberalism","mediation","murmur","stalwart","contractual","incarnation","lesion","chauffeur","embroider","handwritten","instantaneous","primer","publicize","swish","defamatory","fiend","ligament","tot","amplifier","section13","anarchy","archaeology","birthmark","comical","exemplify","mystic","prosthetic","sparrow","whimsical","ammesia","dispel","intangible","underwrite","chisel","sag","diffuse","infidelity","notoriety","showroom","syllable","teem","compulsive","contraband","earmark","enlightenment","poultry","tenor","chaser","chlorine","entrant","executioner","hiatus","nimble","unannouced","astronomical","canvass","concur","sinful","sorority","anus","coincidental","deadlock","eletrode","farce","induct","section14","intersect","latent","lull","lurch","orbital","patty","auditorium","outperform","overcrowded","phishing","respite","rundown","slaugheterhouse","stringer","typhoon","aquatic","bulletin","domino","gong","maize","oblivion","retribution","alum","aneurysm","appreciative","flora","hoot","loner","nasal","pottery","proverbial","quash","scuffle","shortfall","circa","glaucoma","kink","physiology","sundown","sweeten","tactile","bursary","candence","confection","hula","section15","improvisation","kinetic","macaroon","tango","uproot","whaling","cyanide","handheld","misbehave","opaque","sac","spate","anew","barbaric","divulge","flog","foreman","hallowed","meningitis","simplisitic","subversive","uni","bestie","halibut","hipster","insinuate","lore","commencement","dosage","gaff","impenetrable","lavatory","punctuate","sketchy","sluggish","turquoise","woodwork","confetti","crouch","downtime","pretence","regal","sunken","choreographer","cringe"]
#word_list = ["section16","discriminatory","entangle","neutron","nil","optimist","pram","rustle","scurry","undisclosed","adjoin","cheddar","defective","hormonal","illustrious","kiosk","onlooker","pathological","sans","seductive","claustrophbic","enlongate","foggy","noir","pretext","stagnate","vowel","banjo","denomination","reprieve","rosy","thine","apprenticeship","canteen","illustrator","improbable","lumpy","oftentimes","ozone","requisite","squeaky","rationalize","renal","rescind","scourge","smiley","section17","vocation","whisker","congested","dependable","endow","fiasco","outlive","predictability","rectangle","remembrance","academia","anchovy","knead","squish","aperture","circumvent","eulogy","inhuman","leech","mackerel","paranormal","pimple","recline","shale","streamer","anaemia","antiquity","cadre","carefree","dialect","envisage","freshen","frrvolous","geology","snippet","stiletto","turntable","embellish","encapsulate","encase","fasify","ingest","kennel","marzipan","permeate","section18","polio","pursuant","sincerity","squirm","stasis","thyme","tripod","ultimatum","clench","commandment","frester","organically","outlandish","pasty","subtract","bitty","consensual","embattled","enshrine","geologist","squabble","sulk","vista","compulsion","groundwork","gullible","meteorite","phantom","polymer","quiche","retell","anarchist","befit","coo","intermediary","limitless","nozzle","nullify","orchid","proclamation","retaliatory","saucy","shrub","sly","snuff","section19","unscathed","wasteland","burlesque","centrist","confound","constipation","heretic","jostle","landowner","pussycat","veal","vibrator","anoint","devious","diversification","harmonious","kimono","lob","pastime","semantic","archipelago","biggie","hurtle","scoff","sprinter","celebratory","fender","hazy","newbie","roach","blight","deform","diagonal","dowry","dweller","extort","limestone","narcissistic","pharma","pooch","adept","billow","emerald","frantically","hustler","section20","manic","pillage","remission","slant","spectre","upholstery","backhand","caress","cowardice","dun","expatriate","feeble","mangrove","originality","theorize","touchy","urchin","animator","bulldog","frosty","defraud","dugout","fodder","philanthropist","propane","visitation","equitable","midget","ratchet","rebirth","skit","veterinary","bourgeois","bygone","childcare","diocesse","disclaimer","flimsy","indulgence","matriarch","stuffy","tenet","ulcer","boon","enclave"]
#word_list = ["section21","fanfare","fab","dystopian","cavern","caribou","plunger","omen","imperialist","digestion","aft","unruly","turmeric","misstep","meagre","fruitful","cipher","camaraderie","asphalt","timid","pushback","pessimistic","mayoral","malt","jigsaw","islander","epitome","disobedience","desolate","delirious","blowout","superstitious","smudge","sliver","mischievous","glee","adrift","redress","receptive","rad","payload","dismember","characterization","astrological","ordain","flamingo","chieftain","section22","baron","aristocratic","abode","apprehensive","sultry","misfit","laden","fickle","dredge","deduct","crochet","comlacent","animosity","resound","publicist","mitten","incompatible","handout","discretionary","abomination","spruce","punchline","incest","fussy","dud","capitalization","appointee","woeful","vocalist","township","seminal","marsh","envelop","turban","shug","rowdy","reverence","rekindle","rapport","ornate","crumple","sterling","slander","shadowy","barley","acidic","section23","triplet","toothless","signatory","jettison","hypnosis","horoscope","galley","resurrection","tint","hibernate","matt","boiler","eclectic","dietary","sassy","scaffold","stench","materialize","pediatric","quip","waterfront","carton","fetish","profanity","prostate","wearable","auxiliary","buggy","immersive","rationale","snoop","commando","expiray","goof","lemur","outfield","erection","imitation","scold","scoiopath","appease","customary","dissect","fellowship","impostor","stipulate","section24","federation","skim","understate","predicament","resourceful","twig","cervical","cortex","domonic","horseback","obligated","wrapper","duet","lobe","patronize","talisman","traverse","bigotry","chancellor","enrage","handler","inward","picturesque","recitify","deliberation","mindless","mope","pulp","repress","romp","scavenger","bogus","cynic","decompose","nab","aluminium","berth","omit","skillet","daft","ecstatic","electrify","felon","procurement","shilling","spore","section25","adventurer","conspicious","dork","smother","treadmill","payback","pointy","babble","colonist","eerie","moody","toil","tramp","boar","dysfunction","lofty","transfusion","childbirth","frantic","incidence","induction","ceremonial","chute","hearty","orchard","senseless","zinc","befriend","merciless","prestige","treasury","bureaucrat","contentious","steamy","distraught","filler","armpit","bubbly","crayon","piston","beware","fastball","hyper","weaponry","whirl","plural"]
#word_list = ["section26","upright","antimater","displacement","medicinal","outcast","barbarian","bonfire","thong","abyss","bespoke","pelt","photographic","skyscraper","vaginal","anthology","persistence","prehistoric","retract","skewer","wherein","groin","heartless","caterpillar","sublime","wager","whiff","ail","gunpowder","healer","lineage","unspspecting","abound","anatomy","mileage","plunder","prosperous","ruby","trot","uterus","barrage","heave","lifeline","swine","windmill","witchcraft","appropriation","section27","racy","fantasize","pathogen","tandem","cyclic","muzzle","shortcoming","wondrous","bigot","eligibility","hypertension","intrinsic","privy","unsolved","gorge","mutilate","sterile","dissident","enquire","gloomy","prominence","scenic","spearhead","fortnight","reborn","revolver","scrutinize","slider","troupe","vindicate","cavalry","immature","moor","sexism","tether","chariot","congestion","holistic","lonesome","superiority","titan","vapour","bulge","incoherent","screenwriter","accolade","section28","deity","groan","handkerchief","intrusion","persuasive","battleship","hangar","liaison","merciful","spire","trustee","absorptin","geezer","ingenuity","mafia","underpants","apiece","battalion","condone","emigrate","inclination","recede","corny","herring","lessen","metaphorical","transpire","whereby","zest","pout","renounce","arsenic","ballpark","elude","pianist","flux","injunction","orgy","periodic","cumulative","epilepsy","liquidate","maul","plaid","poddle","saucer","section29","taker","accentuate","colon","lyrical","macho","outdo","plethora","saliva","separable","wilful","compulsory","consequent","cull","fluent","geological","giveaway","marrow","quintessential","satin","attire","chump","commune","dormant","ostensible","pebble","screech","validity","vulgar","wreath","cauliflower","condemnation","contingency","machete","moisturize","preoccupy","airspace","ascent","disdain","slender","canon","ghastly","insistence","manicure","nominal","quilt","elicit","section30","entitlement","monetize","whatnot","douse","indispensable","pigment","primate","sauna","silo","ascertain","decoy","humorous","jig","nutritious","aquarium","catchphrase","despicable","expend","obedience","revel","trance","experimentation","snuggle","unwell","alchemy","apricot","floss","paralysis","restrictive","scientifically","anaesthetic","fascism","propeller","slang","adaptor","depreciation","frail","shroud","starch","stauch","youse","mayonnaise","ploy","psyche","saffron","finite"]
#word_list = ["section31","intermediate","mishap","repel","unmanned","checker","complemetary","backstory","ballad","borough","compatibility","discontent","joyous","mussel","ostrich","proliferation","bedding","chum","conglomerate","dean","developmental","shrapnel","bulletproof","forgo","raven","reek","stormy","borderline","brochure","encyclopedia","ethos","quaint","bribery","git","heroism","opium","urinate","cosmos","minion","platoon","viliant","visceral","attributable","uncanny","repetitive","runny","fathom","section32","sanitation","superintendent","abdicate","apocalyptic","fable","geometric","oppressive","scotch","coherent","cyborg","exhilarating","fetal","limbo","omission","retrospective","walrus","bosom","fleece","gradient","invariable","jolt","nucleus","primal","writ","afflict","catchy","bistil","idiotic","plush","swagger","tampon","contour","quirk","rejuvenate","tidal","commonplace","cranky","gimmick","realism","showman","theorist","debit","dreamy","fetus","gloom","impulsive","section33","sift","disinformation","flurry","guerrilla","siphon","arbitration","condense","cuss","deprivation","flutter","potassium","pragmatic","relent","resin","flask","poof","prod","rouse","scorn","giddy","indifference","nicotine","ponytail","cork","fasten","gallop","incidental","paternity","readiness","regroup","trifle","bicker","blurry","chainsaw","mathematician","pathologist","rivet","firecracker","breezy","constable","headmaster","lifeless","pamper","paramount","pedigree","reliant","section34","rhubarb","upscale","burrow","gratify","impoverish","roundabout","scorer","stardom","manhood","oily","revamp","defamation","deforestation","onslaught","payday","undefeated","baseman","theology","aristocrat","eviction","jester","apron","binocular","celestial","grub","hypnotize","intertwine","mush","ordinance","scripture","sporty","alphabet","folly","polarization","rosemary","tremor","austerity","booby","chromosome","cryptic","pesky","reconnaissance","serpent","turret","beckon","clump","section35","continuum","depot","figurative","hostess","instil","keynote","nostril","roadblock","scarcity","sombre","tacky","wrongful","blitz","bystander","collagen","lovable","provisional","purposeful","rightfully","dislocate","expectancy","hymn","localize","partake","stature","treachery","wasp","charade","crossroads","visor","canister","cant","inversion","masquerade","samurai","escalator","fanny","fruity","nudity","psychosis","tendon","balm","combustion","encore","entourage","motif"]
word_list = ["section36","quadrangle","statewide","undervalue","burgeon","dabble","impromptu","doubtful","embroil","sedative","croissant","exclaim","harp","incision","lager","quartet","radiator","refreshment","repent","secluded","advent","cartoonist","moi","plump","glimmer","groundwater","incendiary","sitter","substantive","annext","bulky","metabolic","nook","zap","craftsman","expedite","leafy","precarious","snowflake","stationary","angst","eyelash","lest","mar","recital","rigour","separatist","section37","worshipper","roadside","tresses","autistic","deterrent","emptiness","nefariuos","parsley","stoop","unequivocal","foliage","idyllic","puberty","resuscitate","sulphur","volt","admittedly","clergy","deranged","dusk","exude","interstate","lug","solemn","anaesthesia","backfire","pharmacist","prinnacle","strife","brotherhood","colonize","detrimental","douche","expanse","flamboyant","intolerance","ministerial","noose","penchant","sham","affluent","complicit","ethanol","phial"]
url_list = ['https://dictionary.cambridge.org/us/dictionary/english/', 'https://www.ldoceonline.com/dictionary/']


def scrape_example(url, word):
    opener = urllib.request.build_opener()
    opener.addheaders = [('User-agent', 'Mozilla/5.0')]
    response = opener.open(url + word)
    html_contents = response.read()
    soup = BeautifulSoup(html_contents, 'html.parser')
    example_list = list()
    if "cambridge" in url:
        example_list = example_list + [s.get_text().strip() for s in soup.find_all("div", class_="examp dexamp")]
        example_list = example_list + [s.get_text().strip() for s in soup.find_all("li", class_="eg dexamp hax")]
    else:
        example_list = example_list + [s.get_text().strip() for s in soup.find_all("span", class_="EXAMPLE")]
    return example_list

word_example_dict = dict()
for word in word_list:
    word = word.strip().replace(" ", "")
    print(word)
    time.sleep(1)
    example_list = list()
    for url in url_list:
        example_list = example_list + scrape_example(url, word)
    word_example_dict[word] = example_list

with open('S8.pickle', 'wb') as f:
    pickle.dump(word_example_dict, f)

document = Document()

for word, example_list in word_example_dict.items():
    add_content(word + ":", align='Left', space_before=0, space_after=0, line_spacing=1, font_size=12,
                set_bold=True, set_all_caps=False, set_underline=False)
    for example in example_list:
        add_content(example, align='Left', space_before=0, space_after=0, line_spacing=1, font_size=12,
                    set_bold=False, set_all_caps=False, set_underline=True)

document.save('S8.docx')